apiVersion: v1
kind: Service
metadata:
  name: joy-of-kubernetes-service
  namespace: joyful-apps
  labels:
    app: joy-of-kubernetes
spec:
  type: ClusterIP
  selector:
    app: joy-of-kubernetes # This must match the labels of the pods in your Deployment
  ports:
  - protocol: TCP
    port: 80       # The port the service will be available on within the cluster
    targetPort: 80 # The port the Nginx container is listening on