apiVersion: apps/v1
kind: Deployment
metadata:
  name: joy-of-kubernetes-deployment
  namespace: joyful-apps
  labels:
    app: joy-of-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joy-of-kubernetes
  template:
    metadata:
      labels:
        app: joy-of-kubernetes
    spec:
      # This initContainer will clone the GitHub repo content
      initContainers:
      - name: git-cloner
        image: alpine/git # A small image with git installed
        args:
          - clone
          - --single-branch # Clones only the default branch
          - --depth
          - "1" # Clones only the latest commit to save space and time
          - https://github.com/TatuE/the_joy_of_Kubernetes_site.git # Git file with the web site
          - /usr/share/nginx/html 
        volumeMounts:
        - name: static-site-content # Mount the shared volume
          mountPath: /usr/share/nginx/html
      #Main Nginx container
      containers:
      - name: joy-of-kubernetes-site
        image: nginx:alpine 
        ports:
        - containerPort: 80 
        volumeMounts:
        - name: static-site-content 
          mountPath: /usr/share/nginx/html 
          readOnly: true 

      volumes:
      - name: static-site-content
        emptyDir: {} 
