apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: joy-of-kubernetes-ingressroute
  namespace: joyful-apps
spec:
  entryPoints:
    - websecure # Use the HTTPS entrypoint
  routes:
    - match: Host(`joy.erkinjuntti.eu`) # Your chosen hostname
      kind: Rule
      services:
        - name: joy-of-kubernetes-service # Matches the Service name above
          port: 80                         # Matches the Service port above
  tls:
    certResolver: myresolver # Your Let's Encrypt resolver configured in Traefik
    domains:
      - main: "joy.erkinjuntti.eu" # Primary domain for the SSL certificate