apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: helloworld-ingressroute
  namespace: helloworld
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`hello-world-k3s.erkinjuntti.eu`)
      kind: Rule
      services:
        - name: helloworld-service
          port: 80
  tls:
    certResolver: myresolver 
    domains:
      - main: "hello-world-k3s.erkinjuntti.eu" 