apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld # Or your preferred namespace, e.g., default
  labels:
    app: helloworld
spec:
  replicas: 2 # Start with two instances
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: nginxdemos/hello # A simple hello world Nginx image
        ports:
        - containerPort: 80 # The application inside the container listens on port 80